### ISSUE TITLE
[BUG] - (Change Request) voor data-vl-auto-open

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-info-tile#14]
**Omschrijf het probleem**
Zie Feature request --> https://github.com/milieuinfo/webcomponent-vl-ui-info-tile/issues/9

Ik had de feature request verkeerd beschreven. We willen eigenlijk een attribuut dat de info-tile open of dicht zet. Dus eerder iets als `data-vl-open`. Afhankelijk van de aan- of afwezigheid van dat attribuut willen we dat de tile open of dicht staat. 

**Gewenst gedrag**
zie omschrijving

**Comment by coemans** [comment]
Standaard is een info-tile gesloten, met het `data-vl-auto-open` attribuut kan dit standaard geopend worden. Verdere interactie is mogelijk a.d.h.v. de `toggle`, `open` en `close` API functies. Is er een specifieke reden waarom jullie dit willen bereiken met een attribuut?

**Comment by coemans** [comment]
Voorlopig wordt ticket afgesloten in afwachting van feedback.
