### ISSUE TITLE
[BUG] - Icoon in header titel verschuift wanneer de tekst te lang is

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-info-tile#8]
**Omschrijf het probleem**
De icon verschuift naar beneden wanneer de tekst binnen de header title van info-tile te lang is. 

**Hoe te reproduceren**
Zie https://grups-ontwikkel.omgeving.vlaanderen.be/zoeken

**Gewenst gedrag**
Dat icon op dezelfde hoogte blijft staan

**Screenshots**
<img width="876" alt="Screenshot 2021-01-14 at 16 18 44" src="https://user-images.githubusercontent.com/8820456/104721250-bcf13000-572d-11eb-81c7-7412e3dd1302.png">

**Omgeving (gelieve aan te vullen):**
 - Browser chrome en safari v14

**Comment by FreekRombauts** [comment]
Review done en getest. Icoon blijft nu op de titellijn staan.
