### ISSUE TITLE
[FEATURE] - attribuut of mogelijkheid aanbieden om de info-tile standaard open- of dichtgeklapt te hebben

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-info-tile#9]
**Wat moet er gebeuren**
Bij het implementeren van de info-tile is er binnen DSI al voor één of meerdere UCs de vraag naar boven gekomen om de info-tiles opengeklapt te hebben. Voorlopig was hier een custom implementatie voor voorzien. Maar inmiddels is er op de review van IBO/GRUPS/DSI naar boven gekomen dat de PO's van IBO en GRUPS niet tevreden zijn met de standaard dichtgeklapte info-tiles.

Daarom zouden we graag de optie hebben om deze default open- of dichtgeklapt te hebben.

**Comment by coemans** [comment]
In PR #10 heb ik een auto-open attribuut toegevoegd en de mogelijkheid voorzien om programmatisch te openen en sluiten. Afhankelijk van de situatie kan er ook voor gekozen worden op niet het auto-open attribuut te gebruiken maar de standaard vl-info-tile die automatisch open staat. Als de info-tile niet toggleable moet zijn, lijkt dat eerder aangewezen.
